-- Initial schema for catalog_db: categories 1-N products, entirely
-- self-contained within this database, so category_id is a real foreign
-- key (unlike order-service's customer_id/product_id, which reference
-- another service's database and are deliberately plain columns instead).
-- Flyway applies this migration once, in every environment, so the schema
-- Hibernate validates against (spring.jpa.hibernate.ddl-auto=validate) is
-- always defined here rather than generated from entities.
--
-- No TIMESTAMPTZ columns here: unlike auth_db's token tables, neither
-- categories nor products carries a java.time.Instant column in the README's
-- data model, so the auth-service lesson about Hibernate 6 mapping Instant to
-- TIMESTAMP_UTC (requiring TIMESTAMPTZ) does not apply to this migration.

CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   BIGINT NOT NULL REFERENCES categories (id),
    product_name  VARCHAR(255) NOT NULL,
    unit_price    FLOAT NOT NULL CHECK (unit_price > 0)
);

CREATE INDEX idx_products_category_id ON products (category_id);
