-- Initial schema for order_db: orders plus its idempotency_keys table.
-- Flyway applies this migration once, in every environment, so the schema
-- Hibernate validates against (spring.jpa.hibernate.ddl-auto=validate) is
-- always defined here rather than generated from entities.
--
-- customer_id/product_id are deliberately plain BIGINT columns, never
-- REFERENCES: they identify rows in customer-service's/catalog-service's own
-- databases (customer_db/catalog_db), two different services this one must
-- never query directly. Both are validated synchronously via
-- CustomerClient/ProductClient (OpenFeign) before an order is ever inserted,
-- never via a database-level foreign key. order_id on idempotency_keys is
-- the opposite case: orders and idempotency_keys live in the same order_db,
-- so that one is a real foreign key.
--
-- created_at is TIMESTAMPTZ, not TIMESTAMP: Hibernate 6 maps java.time.Instant
-- to JDBC's TIMESTAMP_UTC by default, which PostgreSQL only accepts as
-- TIMESTAMPTZ (same lesson as auth_db's token tables).

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    quantity    INT NOT NULL CHECK (quantity > 0),
    total       DOUBLE PRECISION NOT NULL,
    status      VARCHAR(50) NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_product_id ON orders (product_id);

CREATE TABLE idempotency_keys (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(255) NOT NULL UNIQUE,
    order_id         BIGINT NOT NULL REFERENCES orders (id),
    created_at       TIMESTAMPTZ NOT NULL
);
