-- Initial schema for auth_db: users <-> roles <-> permissions (RBAC), plus
-- per-user tokens (activation, password reset, JWT blacklist). Flyway applies
-- this migration once, in every environment (dev, test via Testcontainers,
-- prod), so the schema Hibernate validates against
-- (spring.jpa.hibernate.ddl-auto=validate) is always defined here rather
-- than generated from entities.
--
-- Unlike spring-security-tutorial's two-step migration (a plain UNIQUE
-- constraint on users.email in V1, replaced by a case-insensitive unique
-- index in V2), this service starts directly with the case-insensitive
-- index below, since UserRepository.existsByEmailIgnoreCase/
-- findByEmailIgnoreCase already assume case-insensitive uniqueness and there
-- is no prior release depending on the case-sensitive constraint to migrate
-- away from.
--
-- All token timestamp columns are TIMESTAMPTZ, not TIMESTAMP: Hibernate 6
-- maps java.time.Instant to the JDBC TIMESTAMP_UTC type by default, which
-- PostgreSQL's dialect renders as "timestamp with time zone". A plain
-- TIMESTAMP column here would mismatch that mapping and fail
-- spring.jpa.hibernate.ddl-auto=validate at startup.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(50) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    account_locked  BOOLEAN NOT NULL DEFAULT FALSE
);

-- Case-insensitive uniqueness, matching UserRepository.existsByEmailIgnoreCase/
-- findByEmailIgnoreCase: a plain UNIQUE constraint on email would be
-- case-sensitive and would let "Ada@example.com" and "ada@example.com" both
-- pass the application-level check before hitting the database.
CREATE UNIQUE INDEX idx_users_email_lower ON users (LOWER(email));

CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL
);

-- Same rationale as idx_users_email_lower: RoleRepository already exposes
-- findByRoleNameIgnoreCase/existsByRoleNameIgnoreCase, so the real
-- uniqueness guarantee needs to be case-insensitive too.
CREATE UNIQUE INDEX idx_roles_role_name_lower ON roles (LOWER(role_name));

CREATE TABLE permissions (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource VARCHAR(50) NOT NULL,
    action   VARCHAR(50) NOT NULL
);

CREATE TABLE role_user (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL REFERENCES roles (id),
    permission_id BIGINT NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE activation_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id),
    token        VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ,
    validated_at TIMESTAMPTZ
);

CREATE INDEX idx_activation_tokens_user_id ON activation_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    token       VARCHAR(255) NOT NULL,
    type        VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

CREATE TABLE blacklisted_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    token           VARCHAR(768) NOT NULL,
    jti             VARCHAR(255) NOT NULL UNIQUE,
    blacklisted_at  TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    expires_at      TIMESTAMPTZ,
    validated_at    TIMESTAMPTZ
);

CREATE INDEX idx_blacklisted_tokens_user_id ON blacklisted_tokens (user_id);
