-- Initial schema for customer_db: a single customers table. Flyway applies
-- this migration once, in every environment (dev, test via Testcontainers,
-- prod), so the schema Hibernate validates against
-- (spring.jpa.hibernate.ddl-auto=validate) is always defined here rather
-- than generated from entities.
--
-- user_id is deliberately a plain BIGINT column, never a REFERENCES clause:
-- the value it carries identifies a row in auth_db's users table, but
-- auth_db and customer_db are two different databases owned by two
-- different services (README's "Data model" / "Why users and customers stay
-- in separate services"). A foreign key here would require customer_db to
-- see across a service boundary it must never cross; the only supported way
-- to resolve a userId is auth-service's own API. This is the single most
-- important rule of this migration/branch.
--
-- Same case-insensitive uniqueness rationale as auth_db's idx_users_email_lower
-- (see auth-service's V1__init_schema.sql): a plain UNIQUE constraint on email
-- would be case-sensitive and would let "Ada@example.com" and
-- "ada@example.com" both pass an application-level uniqueness check before
-- hitting the database. Chosen here for consistency across services even
-- though the README only spells out "UNIQUE" for this column.
--
-- No TIMESTAMPTZ columns here: unlike auth_db's token tables, the customers
-- table in the README's data model carries no java.time.Instant column, so
-- the auth-service lesson about Hibernate 6 mapping Instant to
-- TIMESTAMP_UTC (requiring TIMESTAMPTZ) does not apply to this migration.

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    telephone  VARCHAR(50) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    address    VARCHAR(255) NOT NULL
);

-- Not a foreign key (see header comment): merely an index, since order-service
-- (and any future consumer) is expected to look up a customer's profile by
-- the auth-service userId that created it.
CREATE INDEX idx_customers_user_id ON customers (user_id);

-- Case-insensitive uniqueness, matching CustomerRepository.findByEmailIgnoreCase.
CREATE UNIQUE INDEX idx_customers_email_lower ON customers (LOWER(email));
